{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk/1.0.0/sdk-1.0.0.module",
    "group": "com.iproov.kmp",
    "module": "sdk",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.3.12"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-iosArm64Main-1.0.0.klib",
          "url": "sdk-iosarm64-1.0.0.klib",
          "size": 73012,
          "sha512": "7cdfb835386851052c4cdf3cac69ec6b574efb5f069a6f20b455857ba43536c705717454aa77f68d74271862f60291b6940215786ab5670ed9359c527b144051",
          "sha256": "f6280b2e6ade6fbc8ba0adf9a13615203ea087ce1b9ea1ef32997273489e8cce",
          "sha1": "ae1c4bfa9738aefeaee35141997b3478fb882a8b",
          "md5": "9f5a040dc1330aeb9b332ca38dea1373"
        },
        {
          "name": "sdk-iosArm64Cinterop-iproovMain-1.0.0.klib",
          "url": "sdk-iosarm64-1.0.0-cinterop-iproov.klib",
          "size": 100098,
          "sha512": "19ea0836f225aec15750a332f64e74a4791b8978dc61a6fbc84e81f6ad1ddda1571f81022306092bddabe1766818cc03d65145dac307a4bd0a543b43661d678e",
          "sha256": "3e8c5308a18a6447cac64d239405a7dc232bc637d745b85ecfbf00f66e5f9c3d",
          "sha1": "5b10aaeef9f5101dd78dfbf6064e318896f4b010",
          "md5": "1c16b3576beb7b6cc9d04ae500411a57"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "sdk-iosarm64-1.0.0-sources.jar",
          "url": "sdk-iosarm64-1.0.0-sources.jar",
          "size": 10158,
          "sha512": "0f7958c59342748b49c53cad9d2724896f324c62ab4fd5c8bdf7c7728b0c9e162d6506adb9899d776c6150e55ae6ac42e672b9c6d1c3f253b9d8ce1145f76b9f",
          "sha256": "f926f23222595c7946d0cad2a9e0eedb13159f4ca1984ef3cbbaf4029f37ee22",
          "sha1": "b2f0e642a24dfa9ba79398994d9bb4407d1b6bb2",
          "md5": "42f17a099db3c1ee57ef6e1201ec6661"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.3.12"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-1.0.0.kotlin_resources.zip",
          "url": "sdk-iosarm64-1.0.0-kotlin_resources.kotlin_resources.zip",
          "size": 324,
          "sha512": "ad7fd0e3de30c1cc3a3e6001d4b0783d6f494250448dbfec8742a29bbb3c0330c67b845aa01c1e5e9bfd99c9abbd88951a3bb673bacaefe8b62754a2f16d207f",
          "sha256": "b7585ee1753e1402529aebbc14767d2032f032773cc26e4bba0545398244ac23",
          "sha1": "0f09bbf68f2f6fa4cdf85d98ed3f7b3db736eeaf",
          "md5": "811ee78619cad0d63ee74bc498567a63"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.3.12"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-iosarm64-1.0.0-metadata.jar",
          "url": "sdk-iosarm64-1.0.0-metadata.jar",
          "size": 261,
          "sha512": "eea9b2dc3e903f572407873228d7eb67a19636ecfdde0f04ffbc272c2404f940b9f9c7a6eef3abe96a94ab92823b8da554db3603c60a116eebf2e0ac38fca380",
          "sha256": "fc489d9779beb2147a53fd3f34911d9ec2619d5f5d9d9381aef09eb0bd91a4cd",
          "sha1": "0f8c229be3bdab2738050b5392669ce5f1d5a1bf",
          "md5": "1a7a629e3afa07b95307ca352f8c2d84"
        }
      ]
    }
  ]
}
