{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk/1.0.0/sdk-1.0.0.module",
    "group": "com.iproov.kmp",
    "module": "sdk",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.3.12"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-iosArm64Main-1.0.0.klib",
          "url": "sdk-iosarm64-1.0.0.klib",
          "size": 72994,
          "sha512": "5cd1736796323fe693fc3f78a31fc39f1775908a47a4696bdcbe6513b0131eed0cf6ebbd6b898c45de2b3173d21045e8fc1bbe75382a8f3e71ef045c06ca7115",
          "sha256": "3e77c49a50429b88485606e54f6bcfe57a1ec302b913cdfe666c24df2c207efe",
          "sha1": "cf2adabb914070594a1a5250edd4f9c18495fc5a",
          "md5": "e65ee8823e87ae9174c4e4fa27f8e4df"
        },
        {
          "name": "sdk-iosArm64Cinterop-iproovMain-1.0.0.klib",
          "url": "sdk-iosarm64-1.0.0-cinterop-iproov.klib",
          "size": 100098,
          "sha512": "09953b16149cde0a1afdc3b52db67053371d94592d599f20371a9ec0caad50405d5a4413a255ee8fcb084276c2248fc408b1920ae89f0eb59e841f62afbfed7b",
          "sha256": "10a0d4de818d592be5cc088a5cababc0af3dfbe1abe9995f27cb911e7c2dedb3",
          "sha1": "90adb155ac8d61ff1dfde2d6601935b06a7bf922",
          "md5": "e560857e4f98514325c361a7e26fe3a1"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "sdk-iosarm64-1.0.0-sources.jar",
          "url": "sdk-iosarm64-1.0.0-sources.jar",
          "size": 10158,
          "sha512": "0f7958c59342748b49c53cad9d2724896f324c62ab4fd5c8bdf7c7728b0c9e162d6506adb9899d776c6150e55ae6ac42e672b9c6d1c3f253b9d8ce1145f76b9f",
          "sha256": "f926f23222595c7946d0cad2a9e0eedb13159f4ca1984ef3cbbaf4029f37ee22",
          "sha1": "b2f0e642a24dfa9ba79398994d9bb4407d1b6bb2",
          "md5": "42f17a099db3c1ee57ef6e1201ec6661"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.3.12"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-1.0.0.kotlin_resources.zip",
          "url": "sdk-iosarm64-1.0.0-kotlin_resources.kotlin_resources.zip",
          "size": 324,
          "sha512": "4af549ea7dcb552a0df296aeff47c34afd452a6e6785e1c938600681bcf08d3de3de1ee931f8e9f4a08bfd49dd7c9406a2e94d8b58b104e221f52c66914d9fdf",
          "sha256": "672b72194eb10f89eac389f80f74d21810ca24d38a372eac60415df1a5462f14",
          "sha1": "b8ccff445ceb5cfd80a225d343c498a68e4ba627",
          "md5": "3e49a550fa57691bca11a5a062ec1f3f"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.3.12"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-iosarm64-1.0.0-metadata.jar",
          "url": "sdk-iosarm64-1.0.0-metadata.jar",
          "size": 261,
          "sha512": "0ca69269e89a7704863b6a132b33182e5a292746ef90abff3c778ca53fb524d58a245080d276a571ee538c3f621d2ca6e719116a764b30bf5a812a40efd118a5",
          "sha256": "ac32133d3453990004d29cb62f1f6d2bee73a18949207472a822db6f1c3e6a22",
          "sha1": "3d7ab57bd97bc67661b0fccc699197101002fbc5",
          "md5": "6d878449bce76007d50c175e6ba86529"
        }
      ]
    }
  ]
}
