{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk/1.0.0/sdk-1.0.0.module",
    "group": "com.iproov.kmp",
    "module": "sdk",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.3.12"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-iosArm64Main-1.0.0.klib",
          "url": "sdk-iosarm64-1.0.0.klib",
          "size": 72997,
          "sha512": "c06c04b3e50d24acbc11d2b45cc95c978f2e9fed9d9f1ca8502898cc99f6aeb6e0be4b76127df442aa4bec4558e02bf1b09e312076dcbe2be1a5b4496744ed89",
          "sha256": "b9dbeebd14015c74e88fedaaa5b04b6371befd3556960824809e927fdace7cb3",
          "sha1": "1f7b4dc2c1674cb82b303bd7fe66a2bdec0d1830",
          "md5": "0150caa5eb636ff76a66fa9b6d5262b1"
        },
        {
          "name": "sdk-iosArm64Cinterop-iproovMain-1.0.0.klib",
          "url": "sdk-iosarm64-1.0.0-cinterop-iproov.klib",
          "size": 100098,
          "sha512": "09953b16149cde0a1afdc3b52db67053371d94592d599f20371a9ec0caad50405d5a4413a255ee8fcb084276c2248fc408b1920ae89f0eb59e841f62afbfed7b",
          "sha256": "10a0d4de818d592be5cc088a5cababc0af3dfbe1abe9995f27cb911e7c2dedb3",
          "sha1": "90adb155ac8d61ff1dfde2d6601935b06a7bf922",
          "md5": "e560857e4f98514325c361a7e26fe3a1"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "sdk-iosarm64-1.0.0-sources.jar",
          "url": "sdk-iosarm64-1.0.0-sources.jar",
          "size": 10158,
          "sha512": "0f7958c59342748b49c53cad9d2724896f324c62ab4fd5c8bdf7c7728b0c9e162d6506adb9899d776c6150e55ae6ac42e672b9c6d1c3f253b9d8ce1145f76b9f",
          "sha256": "f926f23222595c7946d0cad2a9e0eedb13159f4ca1984ef3cbbaf4029f37ee22",
          "sha1": "b2f0e642a24dfa9ba79398994d9bb4407d1b6bb2",
          "md5": "42f17a099db3c1ee57ef6e1201ec6661"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.3.12"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-1.0.0.kotlin_resources.zip",
          "url": "sdk-iosarm64-1.0.0-kotlin_resources.kotlin_resources.zip",
          "size": 324,
          "sha512": "16c5d207a0d43495ea17e43e0521e38d84e8f8ea670ad507fd9a838596172bb169f27e70f7698a751c68487e9482491ebd83d7671f38c96e547e6581a204148a",
          "sha256": "eca30e90fd586f96c707004bcd7cdd80d0f96308287c0c6d4346afb24727b3d1",
          "sha1": "31a182552dc5b6f138cbb90799fef266c0c9630f",
          "md5": "9d6af4172f43d4a133b8d929efd46fc7"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.3.12"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-iosarm64-1.0.0-metadata.jar",
          "url": "sdk-iosarm64-1.0.0-metadata.jar",
          "size": 261,
          "sha512": "7e4c92dc9d61c433a7eedff4d6628e96792daf722292d0609aeffbc236dab1bb498c40e192b78c851e9c3f3097a4aa20bf17547be5c65469bbdc3ab82970ed9f",
          "sha256": "261b7bf2b5741f61bd9aeafa2c87631ce90da22f9be53a66a936621f52b48b5b",
          "sha1": "26b5929aaf4566cece583fa406facab475d2014a",
          "md5": "39dd597ccba28313c6e2467dc43f2ca3"
        }
      ]
    }
  ]
}
