{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk/1.0.1/sdk-1.0.1.module",
    "group": "com.iproov.kmp",
    "module": "sdk",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.3.12"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-iosArm64Main-1.0.1.klib",
          "url": "sdk-iosarm64-1.0.1.klib",
          "size": 73379,
          "sha512": "3df39fddeb55624cd34f8014bbbd7ce68f0362d9b98eed710c0ff6c917b4687548725703c6af3d4065e56070e5ea361c0fb6238e7c38e6d15aef9e9e30694af9",
          "sha256": "849e454c52b94c70e05f1369ab3a646aa65fdb44f8354441895be0ef710f3aa1",
          "sha1": "0e59c79b33e54dd918f132cc28ac77b2ae41a59d",
          "md5": "9e92bd70c2cdcbc95102017acef3a86b"
        },
        {
          "name": "sdk-iosArm64Cinterop-iproovMain-1.0.1.klib",
          "url": "sdk-iosarm64-1.0.1-cinterop-iproov.klib",
          "size": 100097,
          "sha512": "d8891fdae2eaa0f4c93be9a458aedc36fe1c140289c051fb6ea7b1d9a9ed91415b816eff24a5aa37a17d949640fcefa28e85bb530dc3d470ba77d05d9a550fc6",
          "sha256": "3e300228a300295be1abea2d7593645be00be82cdd9bedcc2041e8d59468b990",
          "sha1": "bc90099bf0c9d6b1165728f81ba348686a33e8de",
          "md5": "f09fa2acd5fdfe6bfe94ac850a725f8c"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "sdk-iosarm64-1.0.1-sources.jar",
          "url": "sdk-iosarm64-1.0.1-sources.jar",
          "size": 10249,
          "sha512": "f3711d102592c6c111f21ccf6e240cfd14bba781e6ed793a604af72dd86cdbbcfb37d4da7168bddf09c750c63069d41c6c4300659ca073db11090e55fc7bac7f",
          "sha256": "46a68899e9ba35aee0f7b39c888cd86557eaa43a2a2cd5dd5b412be84c1943c5",
          "sha1": "c6cfac1331aed183618c37c134970aaf85848f8d",
          "md5": "2a0d1ed06f232d2fa0a62a31688580d1"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.3.12"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-1.0.1.kotlin_resources.zip",
          "url": "sdk-iosarm64-1.0.1-kotlin_resources.kotlin_resources.zip",
          "size": 324,
          "sha512": "d8bed4b9bc8931694df29df56ec27a2e808188b8efb6f4974157924160d968d8a8fdf188820d1ca5c0dbddb2d57419913dcf0322265b4d2d05a86eb58ea4a731",
          "sha256": "5f6f408ce51def2b559b9e7ad31e0d51526d793950b73880537d63ee161cf0d5",
          "sha1": "92a25689c6a7354d67f4b5cf6152dcad09e13aad",
          "md5": "c1bfb6d2b90882b9a89aa38f6c96179f"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.3.12"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-iosarm64-1.0.1-metadata.jar",
          "url": "sdk-iosarm64-1.0.1-metadata.jar",
          "size": 261,
          "sha512": "02be91d13074d2f3cbcc12367e714fc9aa70ac5ee43f917f6855fd20d014019800c1e27bb4d8d46e404db7b94649eb7ab33fa4ef417853244318701e4614fc6c",
          "sha256": "72f3d3d68d15122e8c833240a2c383b56f105be0c55af6acdf7d2624657ae014",
          "sha1": "495fc968d93f14e6dcd19795ef3767a10537da5f",
          "md5": "eafc9f10e85f16045e35274512e118b5"
        }
      ]
    }
  ]
}
