{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk/2.0.1/sdk-2.0.1.module",
    "group": "com.iproov.kmp",
    "module": "sdk",
    "version": "2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-debug.aar",
          "url": "sdk-android-debug-2.0.1.aar",
          "size": 88961,
          "sha512": "5a26ce6ac262944aaac7c61ab5f63c7afdd5ac042a142b526b8367acc96f8d0079b116f4cd723f78ee27211231687db72ccad6f3ee1a9a180f88d9bae5313ba1",
          "sha256": "9ecbccf9d3ee8e7d9b24056ae068e5b35539d0676877eb8490161d8256298bcf",
          "sha1": "9bda00309fa95a9b466c9c2d497ae8fdc0ccd7dc",
          "md5": "3d6636f598ee101d45a875824c88339b"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "2.3.12"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.iproov.sdk",
          "module": "iproov",
          "version": {
            "requires": "11.1.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.12"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.12"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.3.12"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-debug.aar",
          "url": "sdk-android-debug-2.0.1.aar",
          "size": 88961,
          "sha512": "5a26ce6ac262944aaac7c61ab5f63c7afdd5ac042a142b526b8367acc96f8d0079b116f4cd723f78ee27211231687db72ccad6f3ee1a9a180f88d9bae5313ba1",
          "sha256": "9ecbccf9d3ee8e7d9b24056ae068e5b35539d0676877eb8490161d8256298bcf",
          "sha1": "9bda00309fa95a9b466c9c2d497ae8fdc0ccd7dc",
          "md5": "3d6636f598ee101d45a875824c88339b"
        }
      ]
    },
    {
      "name": "debugSourcesElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "sdk-android-debug-2.0.1-sources.jar",
          "url": "sdk-android-debug-2.0.1-sources.jar",
          "size": 10603,
          "sha512": "45a6134934f5b85b3da61d3d3f1b40a27f6af0a27bbde112c01222a28b733902a4f2a267e4cbc632ee19ad6b69802c14f2b3a0eb31d30e594c4c6d89655f62c2",
          "sha256": "0047a65c9c2e010e83f61fcda9db4e5ac789e8cf27b74de3cbd2d995042f4687",
          "sha1": "58508e59fdd1912ceb5ca884add39b33b086befe",
          "md5": "cec1a3905555b8884731f5b5dda56a39"
        }
      ]
    }
  ]
}
