{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iproov.kmp",
    "module": "sdk",
    "version": "2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.12"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-2.0.1.jar",
          "url": "sdk-2.0.1.jar",
          "size": 9444,
          "sha512": "fa37f1cdafb87fc55a905dec7c2abf40f3cc17d1f319668428b01e73c6e8896bc00cc8bbf4511baf59fea31ee58ff015a5d20b61db8ca9ecb0499134a2aff1e8",
          "sha256": "705efd8ffe7ec67959d015a9643aeda43cadf44157190c6215f3c78ccb043537",
          "sha1": "f3025ee71ee8e6fad8facd76ab0502ca92d99b08",
          "md5": "862cd8390b4182aa5574e71e219fb5a1"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "sdk-2.0.1-sources.jar",
          "url": "sdk-2.0.1-sources.jar",
          "size": 9972,
          "sha512": "5bfffb24ad14db6de8bc41d769aefbf746b0dcefd03afef654f160c14671210a69a9aff8585af7063bf6d4b35c6f6b8685d39d8f062b7041be3713f3da8c99e5",
          "sha256": "6926f9211d07e55e6f06ace0f2ab1bc37cd44bce6eebacfb7d419ece954ff921",
          "sha1": "c76d08bac5c5427731b8c9402bd9ec1b5b830e1d",
          "md5": "46fb58ea0ffc64d85e4301bee7e7e6c0"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../sdk-android-debug/2.0.1/sdk-android-debug-2.0.1.module",
        "group": "com.iproov.kmp",
        "module": "sdk-android-debug",
        "version": "2.0.1"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../sdk-android-debug/2.0.1/sdk-android-debug-2.0.1.module",
        "group": "com.iproov.kmp",
        "module": "sdk-android-debug",
        "version": "2.0.1"
      }
    },
    {
      "name": "debugSourcesElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../sdk-android-debug/2.0.1/sdk-android-debug-2.0.1.module",
        "group": "com.iproov.kmp",
        "module": "sdk-android-debug",
        "version": "2.0.1"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../sdk-android/2.0.1/sdk-android-2.0.1.module",
        "group": "com.iproov.kmp",
        "module": "sdk-android",
        "version": "2.0.1"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../sdk-android/2.0.1/sdk-android-2.0.1.module",
        "group": "com.iproov.kmp",
        "module": "sdk-android",
        "version": "2.0.1"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../sdk-android/2.0.1/sdk-android-2.0.1.module",
        "group": "com.iproov.kmp",
        "module": "sdk-android",
        "version": "2.0.1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-iosarm64/2.0.1/sdk-iosarm64-2.0.1.module",
        "group": "com.iproov.kmp",
        "module": "sdk-iosarm64",
        "version": "2.0.1"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-iosarm64/2.0.1/sdk-iosarm64-2.0.1.module",
        "group": "com.iproov.kmp",
        "module": "sdk-iosarm64",
        "version": "2.0.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-iosarm64/2.0.1/sdk-iosarm64-2.0.1.module",
        "group": "com.iproov.kmp",
        "module": "sdk-iosarm64",
        "version": "2.0.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-iossimulatorarm64/2.0.1/sdk-iossimulatorarm64-2.0.1.module",
        "group": "com.iproov.kmp",
        "module": "sdk-iossimulatorarm64",
        "version": "2.0.1"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-iossimulatorarm64/2.0.1/sdk-iossimulatorarm64-2.0.1.module",
        "group": "com.iproov.kmp",
        "module": "sdk-iossimulatorarm64",
        "version": "2.0.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-iossimulatorarm64/2.0.1/sdk-iossimulatorarm64-2.0.1.module",
        "group": "com.iproov.kmp",
        "module": "sdk-iossimulatorarm64",
        "version": "2.0.1"
      }
    }
  ]
}
